dist: bionic
language: python
cache: pip
python:
  - 3.6

install:
  # Make a wheel and install it to test to catch possible
  # issues with releases
  - pip install --upgrade setuptools pip
  - pip install -r dev-requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl
  - pip freeze

script:
  - |
    # run autoformat
    if [[ "$REPO_TYPE" == "lint" ]]; then
      pre-commit run --all-files
    fi

after_failure:
  - |
    # point to auto-lint-fix
    if [[ "$REPO_TYPE" == "lint" ]]; then
      echo "You can install pre-commit hooks to automatically run formatting"
      echo "on each commit with:"
      echo "    pre-commit install"
      echo "or you can run by hand on staged files with"
      echo "    pre-commit run"
      echo "or after-the-fact on already committed files with"
      echo "    pre-commit run --all-files"
    fi

matrix:
  include:
    - env:
        - REPO_TYPE=lint
jobs:
  include:
    - stage: deploy
      if: tag IS present
      deploy:
        - provider: pypi
          user: __token__
          # password: $PYPI_PASSWORD
          distributions: sdist bdist_wheel
          on:
            tags: true
